#!/bin/bash
set -eux
set -o pipefail

exec 3>&1 # use fd 3 for script output
exec 1>&2 # send normal stdout to stderr for logging

# read stdin
payload=$(mktemp -d)/aws-kms-resource-input
cat > $payload <&0

version=$(jq -r '.version.version // ""' < $payload)

if [ -n "$version" ]; then
  next_version=$(expr "$version" + 1)
  jq -n '[{ version: $version }]' --arg version "$next_version" >&3
else
  jq -n '[{ version: 0 }]' >&3
fi
