#!/bin/bash
[ "$DEBUG" = "true" ] && set -x
set -eu
set -o pipefail

exec 3>&1 # use fd 3 for script output
exec 1>&2 # send normal stdout to stderr for logging

# always return current time. version will bump every minitue.
jq -n '[{ version: $version }]' --arg version "$(date +%Y%m%d-%H:%M:00)" >&3
