#!/bin/bash
[ "$DEBUG" = "true" ] && set -x
set -eu
set -o pipefail

exec 3>&1 # use fd 3 for script output
exec 1>&2 # send normal stdout to stderr for logging

# read stdin
payload=$(mktemp -d)/aws-kms-resource-input
cat > $payload <&0
version=$(jq -r .version.version < $payload)

jq -n '{
  version: { version: $version },
  metadata: []
}' --arg version "$version" >&3
